# Generated by Django 4.0 on 2022-08-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(default='Tehran', max_length=30, verbose_name='Location')),
                ('capacity', models.IntegerField(verbose_name='Seats')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Contact')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('director', models.CharField(max_length=50, verbose_name='Director')),
                ('year', models.IntegerField(verbose_name='Release Date')),
                ('description', models.TextField(verbose_name='Story')),
                ('length', models.IntegerField(verbose_name='Duration')),
                ('rates', models.CharField(blank=True, choices=[('G', 'General Audience'), ('PG', 'Parental Guidance'), ('PG-13', 'Parental Guidance Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Clearly Adult')], default='PG', max_length=5, null=True, verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('salable_sits', models.IntegerField(verbose_name='Availabe Seats')),
                ('free_sits', models.IntegerField(verbose_name='Number of Seats')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.movie', verbose_name='Title')),
            ],
        ),
    ]
